# Importing Essential Libraries

In [1]:
import pandas as pd

# Reading CSV File

In [2]:
df=pd.read_csv('INDIAN BANK-CLEANUP FILE.csv')

In [3]:
df.shape

(4015, 8)

In [4]:
df.tail(5)

,DATE,DESCRIPTION,DEBIT,CREDIT,BALANCE,CLASSIFICATION_TRANS,Unnamed: 6,Unnamed: 7
4010,31-01-2020,SERVICEBRANCHCHENNAICHEQUEDEPO00001264CRICICIB...,NaN,2151.0,1807012.3,CHQ,1807012.3,0.0
4011,31-01-2020,ATMSERVICEWITHDRAWALTRANSFER IMPS P2A 00311215...,31320.0,NaN,1775692.3,IMPS,1775692.3,0.0
4012,31-01-2020,ATMSERVICEWITHDRAWALTRANSFER IMPSCOMMISSIONCHA...,6.0,NaN,1775686.3,BANK-CHARGES,1775686.3,0.0
4013,31-01-2020,MUMBAIFORTC ACFEESM SCRMADRASAGRO273TRANSFER23,NaN,2486.0,1778172.3,TRANSFER,1778172.3,0.0
4014,31-01-2020,ATMSERVICEBYTRANSFERCRBRANCH/IMPS/027/Personal...,NaN,10092.0,1788264.3,IMPS,1788264.3,0.0

In [5]:
df.dtypes

DATE                     object
DESCRIPTION              object
DEBIT                   float64
CREDIT                  float64
BALANCE                 float64
CLASSIFICATION_TRANS     object
Unnamed: 6              float64
Unnamed: 7              float64
dtype: object

## Data Cleaning

In [6]:
# Drop the last two columns
df.drop(df.columns[-2:], axis=1, inplace=True)

# Display the updated DataFrame
df

,DATE,DESCRIPTION,DEBIT,CREDIT,BALANCE,CLASSIFICATION_TRANS
0,01-02-2019,TIRUMANGALAMBYCHQ TTTFRCRKISHOREMARKETING,NaN,2828.0,735041.64,CHQ
1,01-02-2019,MUMBAIFORTWITHDRAWALTRANSFERMARSINTERNATIONAID...,500029.0,NaN,235012.64,TRANSFER
2,01-02-2019,MUMBAIFORTC ACFEESSRICRMEENAKSHIAM729TRANSFER24,NaN,3577.0,238589.64,TRANSFER
3,01-02-2019,MUMBAIFORTC ACFEESCRAMMANFRUITS764TRANSFER23,NaN,32477.0,271066.64,TRANSFER
4,02-02-2019,SERVICEBRANCHCHENNAICHEQUEDEPO00019876CRANDHRA...,NaN,20575.0,291641.64,CHQ
...,...,...,...,...,...,...
4010,31-01-2020,SERVICEBRANCHCHENNAICHEQUEDEPO00001264CRICICIB...,NaN,2151.0,1807012.30,CHQ
4011,31-01-2020,ATMSERVICEWITHDRAWALTRANSFER IMPS P2A 00311215...,31320.0,NaN,1775692.30,IMPS
4012,31-01-2020,ATMSERVICEWITHDRAWALTRANSFER IMPSCOMMISSIONCHA...,6.0,NaN,1775686.30,BANK-CHARGES
4013,31-01-2020,MUMBAIFORTC ACFEESM SCRMADRASAGRO273TRANSFER23,NaN,2486.0,1778172.30,TRANSFER
4014,31-01-2020,ATMSERVICEBYTRANSFERCRBRANCH/IMPS/027/Personal...,NaN,10092.0,1788264.30,IMPS

## Parsing Date

In [7]:
df['DATE'] = pd.to_datetime(df['DATE'], format="%d-%m-%Y", errors='coerce')

In [8]:
df.tail(10)

,DATE,DESCRIPTION,DEBIT,CREDIT,BALANCE,CLASSIFICATION_TRANS
4005,2020-01-30,MUMBAIFORTC ACFEESCRSANTHOSHSUPERM106TRANSFER29,NaN,450.0,1794367.3,TRANSFER
4006,2020-01-30,MUMBAIFORTC ACFEESCRANNACHIENTE8891674TRANSFER26,NaN,5587.0,1799954.3,TRANSFER
4007,2020-01-30,MUMBAIFORTC ACFEESKPNCRFARMFRESHP437TRANSFER20,NaN,3438.0,1803392.3,TRANSFER
4008,2020-01-30,CASHDEPCRCHRGSOTHER,100.0,NaN,1803292.3,DEPOSIT-CHARGES
4009,2020-01-31,SERVICEBRANCHCHENNAICHEQUEDEPO00000387CRICICIB...,NaN,1569.0,1804861.3,CHQ
4010,2020-01-31,SERVICEBRANCHCHENNAICHEQUEDEPO00001264CRICICIB...,NaN,2151.0,1807012.3,CHQ
4011,2020-01-31,ATMSERVICEWITHDRAWALTRANSFER IMPS P2A 00311215...,31320.0,NaN,1775692.3,IMPS
4012,2020-01-31,ATMSERVICEWITHDRAWALTRANSFER IMPSCOMMISSIONCHA...,6.0,NaN,1775686.3,BANK-CHARGES
4013,2020-01-31,MUMBAIFORTC ACFEESM SCRMADRASAGRO273TRANSFER23,NaN,2486.0,1778172.3,TRANSFER
4014,2020-01-31,ATMSERVICEBYTRANSFERCRBRANCH/IMPS/027/Personal...,NaN,10092.0,1788264.3,IMPS

In [9]:
df.dtypes

DATE                    datetime64[ns]
DESCRIPTION                     object
DEBIT                          float64
CREDIT                         float64
BALANCE                        float64
CLASSIFICATION_TRANS            object
dtype: object

# Converting to numeric values

In [10]:
df['DEBIT'] = pd.to_numeric(df['DEBIT'], errors='coerce')
df['CREDIT'] = pd.to_numeric(df['CREDIT'], errors='coerce')
df['BALANCE'] = pd.to_numeric(df['BALANCE'], errors='coerce')

df.tail()

,DATE,DESCRIPTION,DEBIT,CREDIT,BALANCE,CLASSIFICATION_TRANS
4010,2020-01-31,SERVICEBRANCHCHENNAICHEQUEDEPO00001264CRICICIB...,NaN,2151.0,1807012.3,CHQ
4011,2020-01-31,ATMSERVICEWITHDRAWALTRANSFER IMPS P2A 00311215...,31320.0,NaN,1775692.3,IMPS
4012,2020-01-31,ATMSERVICEWITHDRAWALTRANSFER IMPSCOMMISSIONCHA...,6.0,NaN,1775686.3,BANK-CHARGES
4013,2020-01-31,MUMBAIFORTC ACFEESM SCRMADRASAGRO273TRANSFER23,NaN,2486.0,1778172.3,TRANSFER
4014,2020-01-31,ATMSERVICEBYTRANSFERCRBRANCH/IMPS/027/Personal...,NaN,10092.0,1788264.3,IMPS

In [11]:
df.dtypes

DATE                    datetime64[ns]
DESCRIPTION                     object
DEBIT                          float64
CREDIT                         float64
BALANCE                        float64
CLASSIFICATION_TRANS            object
dtype: object

## Handling NaN

In [12]:
df['DEBIT'] = df['DEBIT'].fillna(0)
df['CREDIT'] = df['CREDIT'].fillna(0)
df['BALANCE'] = df['BALANCE'].fillna(0)

df.tail(5)

,DATE,DESCRIPTION,DEBIT,CREDIT,BALANCE,CLASSIFICATION_TRANS
4010,2020-01-31,SERVICEBRANCHCHENNAICHEQUEDEPO00001264CRICICIB...,0.0,2151.0,1807012.3,CHQ
4011,2020-01-31,ATMSERVICEWITHDRAWALTRANSFER IMPS P2A 00311215...,31320.0,0.0,1775692.3,IMPS
4012,2020-01-31,ATMSERVICEWITHDRAWALTRANSFER IMPSCOMMISSIONCHA...,6.0,0.0,1775686.3,BANK-CHARGES
4013,2020-01-31,MUMBAIFORTC ACFEESM SCRMADRASAGRO273TRANSFER23,0.0,2486.0,1778172.3,TRANSFER
4014,2020-01-31,ATMSERVICEBYTRANSFERCRBRANCH/IMPS/027/Personal...,0.0,10092.0,1788264.3,IMPS

# Analyze Data

## Calculate Total Income

In [13]:
Sum_credit = df['CREDIT'].sum()

print("Total Income:", Sum_credit)

Total Income: 86109827.09

## Calculate Total Expenses

In [14]:
Sum_debit = df['DEBIT'].sum()

print("Total Expenses:", Sum_debit)

Total Expenses: 85053776.42999999

## Identifying Frequent Transactions

In [15]:
top_frequent_transactions = df.groupby('DESCRIPTION').size().sort_values(ascending=False).head(5)

print("Top 5 Most Frequent Transaction Descriptions:")
print(top_frequent_transactions)

Top 5 Most Frequent Transaction Descriptions:
DESCRIPTION
TIRUMANGALAMCASHDEPOSITCRDepositbySELF              184
SERVICEBRANCHCHENNAICHQDISHONOURCR                   80
TIRUMANGALAMBYCHQ TTTFRCRKISHOREMARKETING            70
SERVICEBRANCHCHENNAIOUTCHQRETCRFundsinsufficient     66
CASHDEPCRCHRGSOTHER                                  64
dtype: int64

In [16]:
df.dtypes

DATE                    datetime64[ns]
DESCRIPTION                     object
DEBIT                          float64
CREDIT                         float64
BALANCE                        float64
CLASSIFICATION_TRANS            object
dtype: object

# Report Generation

In [17]:
report_df = df[["DATE", "DEBIT", "CREDIT"]]

In [18]:
report_df.dtypes

DATE      datetime64[ns]
DEBIT            float64
CREDIT           float64
dtype: object

In [19]:
report_df["DATE"] = report_df["DATE"].dt.strftime("%Y-%m")

C:\Users\admin\AppData\Local\Temp\ipykernel_22264\2599620418.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  report_df["DATE"] = report_df["DATE"].dt.strftime("%Y-%m")

In [20]:
report_df

         DATE     DEBIT   CREDIT
0     2019-02       0.0   2828.0
1     2019-02  500029.0      0.0
2     2019-02       0.0   3577.0
3     2019-02       0.0  32477.0
4     2019-02       0.0  20575.0
...       ...       ...      ...
4010  2020-01       0.0   2151.0
4011  2020-01   31320.0      0.0
4012  2020-01       6.0      0.0
4013  2020-01       0.0   2486.0
4014  2020-01       0.0  10092.0

[4015 rows x 3 columns]

In [21]:
report_df = report_df.groupby("DATE").sum().reset_index()

In [22]:
report_df.columns

Index(['DATE', 'DEBIT', 'CREDIT'], dtype='object')

In [23]:
report_df

       DATE       DEBIT       CREDIT
0   2019-02  5422616.00   6021886.00
1   2019-03  6824110.00   6321991.00
2   2019-04  5370209.78   6296712.00
3   2019-05  5935334.00   4739062.00
4   2019-06  4895765.00   4610699.75
5   2019-07  6379826.52   7635172.00
6   2019-08  8968762.04   7725705.69
7   2019-09  6670255.83   9003463.05
8   2019-10  9120393.38  13777948.94
9   2019-11  8710208.38   7082776.00
10  2019-12  8359600.12   5502005.00
11  2020-01  8396695.38   7392405.66

In [24]:
balance_df = df[["DATE", "DEBIT", "CREDIT", "BALANCE"]]

In [25]:
balance_df

           DATE     DEBIT   CREDIT     BALANCE
0    2019-02-01       0.0   2828.0   735041.64
1    2019-02-01  500029.0      0.0   235012.64
2    2019-02-01       0.0   3577.0   238589.64
3    2019-02-01       0.0  32477.0   271066.64
4    2019-02-02       0.0  20575.0   291641.64
...         ...       ...      ...         ...
4010 2020-01-31       0.0   2151.0  1807012.30
4011 2020-01-31   31320.0      0.0  1775692.30
4012 2020-01-31       6.0      0.0  1775686.30
4013 2020-01-31       0.0   2486.0  1778172.30
4014 2020-01-31       0.0  10092.0  1788264.30

[4015 rows x 4 columns]

In [26]:
balance_df["DATE"] = balance_df["DATE"].dt.strftime("%Y-%m")

C:\Users\admin\AppData\Local\Temp\ipykernel_22264\4038409200.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  balance_df["DATE"] = balance_df["DATE"].dt.strftime("%Y-%m")

In [27]:
balance_df

         DATE     DEBIT   CREDIT     BALANCE
0     2019-02       0.0   2828.0   735041.64
1     2019-02  500029.0      0.0   235012.64
2     2019-02       0.0   3577.0   238589.64
3     2019-02       0.0  32477.0   271066.64
4     2019-02       0.0  20575.0   291641.64
...       ...       ...      ...         ...
4010  2020-01       0.0   2151.0  1807012.30
4011  2020-01   31320.0      0.0  1775692.30
4012  2020-01       6.0      0.0  1775686.30
4013  2020-01       0.0   2486.0  1778172.30
4014  2020-01       0.0  10092.0  1788264.30

[4015 rows x 4 columns]

In [28]:
## Finding last transaction balance of each month

final_balance = balance_df.groupby("DATE")["BALANCE"].last()

In [29]:
## merging final balance of each month with new dataframe

report_df["BALANCE"] = report_df["DATE"].map(final_balance)

In [30]:
report_df

       DATE       DEBIT       CREDIT     BALANCE
0   2019-02  5422616.00   6021886.00  1331483.64
1   2019-03  6824110.00   6321991.00   829364.64
2   2019-04  5370209.78   6296712.00  1755866.86
3   2019-05  5935334.00   4739062.00   559594.86
4   2019-06  4895765.00   4610699.75   274529.61
5   2019-07  6379826.52   7635172.00  1529875.09
6   2019-08  8968762.04   7725705.69   286818.74
7   2019-09  6670255.83   9003463.05  2620025.96
8   2019-10  9120393.38  13777948.94  7277581.52
9   2019-11  8710208.38   7082776.00  5650149.14
10  2019-12  8359600.12   5502005.00  2792554.02
11  2020-01  8396695.38   7392405.66  1788264.30

In [31]:
## writing this dataframe to new csv file

report_df.to_csv('monthly_summary_INDIAN_BANK.csv', index=False)

## Identifying Frequent Transactions

In [32]:
top_frequent_transactions = df.groupby('DESCRIPTION').size().sort_values(ascending=False).head(5)

print("Top 5 Most Frequent Transaction Descriptions:")
print(top_frequent_transactions)

Top 5 Most Frequent Transaction Descriptions:
DESCRIPTION
TIRUMANGALAMCASHDEPOSITCRDepositbySELF              184
SERVICEBRANCHCHENNAICHQDISHONOURCR                   80
TIRUMANGALAMBYCHQ TTTFRCRKISHOREMARKETING            70
SERVICEBRANCHCHENNAIOUTCHQRETCRFundsinsufficient     66
CASHDEPCRCHRGSOTHER                                  64
dtype: int64

## Identifying Inconsistencies in BALANCE

In [33]:
balance = df.iloc[0]["BALANCE"]
credit = df.iloc[0]["CREDIT"]
debit = df.iloc[0]["DEBIT"]
initial_balance = balance - credit + debit

In [34]:
list_balance = []
current_balance = initial_balance

for index, row in report_df.iterrows():
    total_balance = current_balance + row["CREDIT"] - row["DEBIT"]
    list_balance.append(total_balance)
    current_balance = total_balance

In [35]:
list_balance

[np.float64(1331483.6399999997),
 np.float64(829364.6399999997),
 np.float64(1755866.8599999994),
 np.float64(559594.8599999994),
 np.float64(274529.6099999994),
 np.float64(1529875.0899999999),
 np.float64(286818.7400000002),
 np.float64(2620025.960000001),
 np.float64(7277581.52),
 np.float64(5650149.139999999),
 np.float64(2792554.0199999986),
 np.float64(1788264.2999999989)]

In [36]:
report_df["Calculated_Balance"] = list_balance
report_df

       DATE       DEBIT       CREDIT     BALANCE  Calculated_Balance
0   2019-02  5422616.00   6021886.00  1331483.64          1331483.64
1   2019-03  6824110.00   6321991.00   829364.64           829364.64
2   2019-04  5370209.78   6296712.00  1755866.86          1755866.86
3   2019-05  5935334.00   4739062.00   559594.86           559594.86
4   2019-06  4895765.00   4610699.75   274529.61           274529.61
5   2019-07  6379826.52   7635172.00  1529875.09          1529875.09
6   2019-08  8968762.04   7725705.69   286818.74           286818.74
7   2019-09  6670255.83   9003463.05  2620025.96          2620025.96
8   2019-10  9120393.38  13777948.94  7277581.52          7277581.52
9   2019-11  8710208.38   7082776.00  5650149.14          5650149.14
10  2019-12  8359600.12   5502005.00  2792554.02          2792554.02
11  2020-01  8396695.38   7392405.66  1788264.30          1788264.30

## Bonus Question(Finding inconsistency in balance)

In [37]:
# function to check for inconsistency
def check_inconsistency(row, previous_balance):
    i_balance = previous_balance - row['DEBIT'] + row['CREDIT']
    return abs(row['BALANCE'] - i_balance) <= 0.01


# Adding a column for inconsistency
previous_balance = initial_balance
inconsistencies = []

for _, row in df.iterrows():
    is_consistent = check_inconsistency(row, previous_balance)
    inconsistencies.append(is_consistent)
    previous_balance = row['BALANCE']  # Update the previous balance for the next row

df['Consistency'] = inconsistencies

df

,DATE,DESCRIPTION,DEBIT,CREDIT,BALANCE,CLASSIFICATION_TRANS,Consistency
0,2019-02-01,TIRUMANGALAMBYCHQ TTTFRCRKISHOREMARKETING,0.0,2828.0,735041.64,CHQ,True
1,2019-02-01,MUMBAIFORTWITHDRAWALTRANSFERMARSINTERNATIONAID...,500029.0,0.0,235012.64,TRANSFER,True
2,2019-02-01,MUMBAIFORTC ACFEESSRICRMEENAKSHIAM729TRANSFER24,0.0,3577.0,238589.64,TRANSFER,True
3,2019-02-01,MUMBAIFORTC ACFEESCRAMMANFRUITS764TRANSFER23,0.0,32477.0,271066.64,TRANSFER,True
4,2019-02-02,SERVICEBRANCHCHENNAICHEQUEDEPO00019876CRANDHRA...,0.0,20575.0,291641.64,CHQ,True
...,...,...,...,...,...,...,...
4010,2020-01-31,SERVICEBRANCHCHENNAICHEQUEDEPO00001264CRICICIB...,0.0,2151.0,1807012.30,CHQ,True
4011,2020-01-31,ATMSERVICEWITHDRAWALTRANSFER IMPS P2A 00311215...,31320.0,0.0,1775692.30,IMPS,True
4012,2020-01-31,ATMSERVICEWITHDRAWALTRANSFER IMPSCOMMISSIONCHA...,6.0,0.0,1775686.30,BANK-CHARGES,True
4013,2020-01-31,MUMBAIFORTC ACFEESM SCRMADRASAGRO273TRANSFER23,0.0,2486.0,1778172.30,TRANSFER,True
4014,2020-01-31,ATMSERVICEBYTRANSFERCRBRANCH/IMPS/027/Personal...,0.0,10092.0,1788264.30,IMPS,True

In [38]:
# printing the rows where balance is inconsistent
df[df['Consistency'] == False]

Empty DataFrame
Columns: [DATE, DESCRIPTION, DEBIT, CREDIT, BALANCE, CLASSIFICATION_TRANS, Consistency]
Index: []